### ISSUE TITLE
[Feature request] Swimmer plot 

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#1010]
This came up during the conference useR/Basel. To discuss

**Comment by ddsjoberg** [comment]
FWIW, I am collaborating with some folks at CHOP to implement an easy swimmers plot grammar in an R package. If any specific needs were mentioned, we can make sure they are implemented. When it's done, we discussing submitting to pharmaverse.

The proposed API would look something like this:

```r
data |>
  ggswim(id = USUBJID, color = TRTGROUP) +
  add_marker(column = death, marker = "\u2715") + # we support unicode shapes
  add_marker(column = trt_end, marker = ❌ )            # as well as emojis...cute! 
```

**Comment by Melkiades** [comment]
@ClaudiaCarlucci for specific. Is there a version already in `teal.osprey` @danielinteractive ?

**Comment by danielinteractive** [comment]
I am not sure, I think @npaszty could know

**Comment by npaszty** [comment]
@Melkiades 
if you mean swim lane plot then yes, there is a function in the osprey package.
https://insightsengineering.github.io/osprey/latest-tag/
