### ISSUE TITLE
[Question]: why h_adsl_adlb_merge_using_worst_flag calls `df_explicit_missing` inside the function

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#1019]
### What is your question?

`df_explicit_missing` is a dangerous step that affect the whole data. It should be executed by the user, like here 
![image](https://github.com/insightsengineering/tern/assets/36079400/04554241-f90f-4168-a97b-d442f5b8d017)

however when in 
![image](https://github.com/insightsengineering/tern/assets/36079400/e2ec580a-4384-4459-ad3a-ffc600a23a7a)
if the h_adsl_adlb_merge_using_worst_flag also contain the `df_explicit_missing` it can be too much for this function

reference: https://insightsengineering.github.io/tlg-catalog/tables/lab-results/lbt14.html

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by shajoezhu** [comment]
agree， `df_explicit_missing` is probably too aggressive
