### ISSUE TITLE
CRAN feedback 

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#1029]
* checking Rd \usage sections ... WARNING

- [x] Documented arguments not in \usage in documentation object ‘assertions’:
  ‘(`integer`)\cr’ ‘...’

- [x] Documented arguments not in \usage in documentation object ‘desctools_binom’:

  ‘grp’

- [x] Documented arguments not in \usage in documentation object ‘h_glm_count’:

  ‘`weights`(`character`)\cr’ ‘`distribution`(`character`)\cr’ ‘`arm`’

- [x] Documented arguments not in \usage in documentation object ‘incidence_rate’:

  ‘person_years’ ‘alpha’

- [x] Documented arguments not in \usage in documentation object ‘prop_diff_test’:

  ‘tbl’

- [x] Documented arguments not in \usage in documentation object ‘response_subgroups’:

  ‘data’ ‘groups_lists’ ‘label_all’ ‘method’

- [x] Documented arguments not in \usage in documentation object ‘survival_duration_subgroups’:

  ‘data’ ‘groups_lists’ ‘label_all’

**Comment by Melkiades** [comment]
It is weird that this was not caught before
