### ISSUE TITLE
 adding count_by.integer function [original Question]: why CMSEQ and MHSEQ should be character/factors?

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#1062]
### What is your question?

according to sdtm ig, MHSEQ and CMSEQ should be numbers instead of character or factors, but in `analyze_num_patients` if there is `count_by`, it requires that MHSEQ and CMSEQ should be character/factors.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
I do not know exactly the logic behind, but if you look at the lowest level analysis function, if you specify `count_by` you get the following:
 ```r
 if (!is.null(count_by)) {
    checkmate::assert_vector(count_by, len = length(x))
    checkmate::assert_multi_class(count_by, classes = c("factor", "character"))
    count2 <- n_available(unique(interaction(x, count_by)))
  }
```
and from this seemingly unnecessary switch:
```r
 y <- switch(as.numeric(!is.null(count_by)) + 1,
    NULL,
    df[[count_by]]
  )
```
I think it is supposed to be a factor as the function interaction works only with those. What you think @ayogasekaram ?

**Comment by shajoezhu** [comment]
I was wondering in sdtm ig, MHSEQ and CMSEQ were numbers, was it because there is the ordering we should also consider, so they made it numeric? My intuition is that we could make them factors with orders.

**Comment by clarkliming** [comment]
the ordering is not important, but it is derived from the ordere of these records. But, since the standards are there, it is not good to change the standard until there is a new standard.

**Comment by clarkliming** [comment]
so it is best to allow "int" in MHSEQ, CMSEQ (in count_by) in tern to make it compatible with the standard data

**Comment by shajoezhu** [comment]
adding `count_by.integer` function

**Comment by clarkliming** [comment]
> adding `count_by.integer` function

https://github.com/insightsengineering/tern/blob/3dc1719958c6652f033d8394c31fc910fb4e50f2/R/summarize_num_patients.R#L50

it seems that this is not a method but some simple class assertions
