### ISSUE TITLE
Update tests for plots to image snaps.

### ISSUE THREAD

**Issue by ayogasekaram** [insightsengineering/tern#1086]
like [this example](https://github.com/insightsengineering/tern/tree/main/tests/testthat/_snaps/g_km)

- [x] g_km
- [x] g_lineplot
- [x] g_step 
- [x] g_forest
- [x] g_waterfall

**Comment by edelarua** [comment]
@ayogasekaram there are probably more `g_km` tests left to do since old tests were never converted.
