### ISSUE TITLE
argument name is misleading for g_lineplot

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#1105]
strata_var and cohort_id is used as argument name, but this is really misleading

https://github.com/insightsengineering/tern/blob/6b3cb0cb6c323e38523ba2315bcae4f4f6f77628/R/g_lineplot.R#L487

**Comment by shajoezhu** [comment]
TODO

replacing `strata` to `group_var` @param group_var (`character` or `NA`)\cr group variable name.
replacing `cohord_id` to `subject_var` @param subject_var(`character` or `NA`)\cr subject variable name.

at `control_lineplot_vars` function and `g_lineplot` functions

**Comment by clarkliming** [comment]
this may have large impact to downstream code so maybe good to be cautious (not need to be released in this time I think)

**Comment by ayogasekaram** [comment]
downstream packages to update:

- [ ] tmc
- [ ] chevron
- [ ] tlg-c
