### ISSUE TITLE
Investigate feasibility of exclusively using `ggplot2` for all plots

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/tern#1109]
Currently all but two plotting functions exclusively use `ggplot2`. These two functions were implemented using `grob`s to avoid issues when combining plots with accompanying annotation tables.

Look into feasibility of converting the following functions to use only `ggplot2` (i.e. `geom_text`) instead of `grob`s:

- [ ] `g_km`
- [x] `g_forest` https://github.com/insightsengineering/tern/pull/1158

**Comment by edelarua** [comment]
Another option for forest plots: https://github.com/insightsengineering/sme-tasks/issues/433

**Comment by edelarua** [comment]
`g_forest`:

- [ ] https://github.com/insightsengineering/tern/pull/1158
- [ ] https://github.com/insightsengineering/teal.modules.clinical/pull/911
- [ ] https://github.com/insightsengineering/chevron/pull/716
- [ ] https://github.com/insightsengineering/tlg-catalog/pull/183
- [ ] https://github.com/insightsengineering/scda.test/pull/87

**Comment by shajoezhu** [comment]
Hi @edelarua , I have created a new issue to follow up on the g_km part, I think we can close this one for now
