### ISSUE TITLE
[Feature Request]: Improve documentation for analyze_vars()

### ISSUE THREAD

**Issue by kieranjmartin** [insightsengineering/tern#1117]
### Feature description

As of version 0.9.2, the help page for `analyze_vars` begins by describing in some detail `s_summary`, and gives a great deal of usage for it. If I understand correctly, I think `analyze_vars` is calling `s_summary` to do summary stats, although I'm not quite sure. Either way, I don't think this is a good use case for a shared help page, and for a core tern function, I think this makes it much more confusing as to how to properly use `analyze_vars`. In particular, it isn't immediately obvious which stats are usable for which object types; you can sort of work it out by looking at the returned list for each class, but that's a very roundabout way of delivering the information!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by edelarua** [comment]
Sounds good! I'll make a separate PR to tidy up the documentation.
