### ISSUE TITLE
Improve readability of analyze function documentation

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/tern#1130]
Similar to https://github.com/insightsengineering/tern/pull/1129, make it easier for the user to read & find information about the analyze function on shared documentation pages. Since statistics/analysis functions are not intended for use by the average `tern` user, we can give the analyze functions precendence in documentation pages by assigning them the `@order 1` roxygen tag.

**Comment by Melkiades** [comment]
Thanks for this Emily!! Reading your comment here, I was thinking that we might add the list of summary functions to the README and intro vignette so to show users how to check if their functionality is already somehow present. What do you think?

**Comment by edelarua** [comment]
Sounds good! I think any vignette changes should definitely be in a separate issue if you want to create one for that.

**Comment by Melkiades** [comment]
@edelarua fantastic job!! :)
