### ISSUE TITLE
[Feature Request]: adding riskdiff columns for all arms other than placebo

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/tern#1142]
### Feature description

I see the `add_risk_diff` function which can be used as a split function, but it is asserting that `arm_y` (ie the non-reference) is length 1:

https://github.com/insightsengineering/tern/blob/685fd9f1094ed1b8bfbc5e589ca37059af7fd66e/R/riskdiff.R#L39

In at least some of the shells I'm seeing, we need a risk-difference column for every non-placebo arm where it is compared against placebo. 

I don't see a way of doing that with the current tern risk-difference implementation (please correct me if i'm wrong on that).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by edelarua** [comment]
Hi @gmbecker, I have implemented a solution for this which is now available in tern v0.9.2.9019.
