### ISSUE TITLE
In `count_occurrences_by_grade` the options `remove_single` and `grade_groups` seems not to cooperate as intended

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#1161]
When removing singles we should get only the grade groups while only "5" is removed. I think the problem resides in `h_append_grade_groups`
```r
library(dplyr)
library(tern)
library(scda)

adsl <- synthetic_cdisc_dataset("latest", "adsl")
adae <- synthetic_cdisc_dataset("latest", "adae")

# Ensure character variables are converted to factors and empty strings and NAs are explicit missing levels.
adsl <- df_explicit_na(adsl) %>% filter(TRT01A != "<Missing>")
adae <- df_explicit_na(adae) %>%
  var_relabel(
    AEBODSYS = "MedDRA System Organ Class",
    AEDECOD = "MedDRA Preferred Term"
  ) %>%
  filter(
    ANL01FL == "Y",
    AETOXGR != "<Missing>"
  )

# Pre-Processing
grade_groups <- list(
  "Grade 1-2" = c("1", "2"),
  "Grade 3-4" = c("3", "4"),
  "Grade 5" = "5"
)

# Create a function to map levels
map_levels <- function(x) {
  ifelse(x %in% c("1", "2"), "Grade 1-2",
         ifelse(x %in% c("3", "4"), "Grade 3-4", "Grade 5"))
}

# Apply the mapping function to the original vector
adae$AETOXGR <- as.factor(map_levels(as.character(adae$AETOXGR)))
adae$TOTAL_VAR <- "- Any adverse events - "

raw_table <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ACTARM") %>%
  split_rows_by(
    var = "TOTAL_VAR",
    label_pos = "hidden",
    child_labels = "visible",
    indent_mod = -1L
  ) %>%
  count_occurrences_by_grade(
    var = "AETOXGR",
    grade_groups = grade_groups,
    .indent_mods = 14L,
    remove_single = TRUE
  ) %>% 
  append_topleft("                            Grade") %>%
  build_table(adae, alt_counts_df = adsl) %>% 
  print()


```

**Comment by edelarua** [comment]
Hi @Melkiades,

I looked into this and I think the correct behaviour is already in place. The `remove_single` option is used to remove the numbered rows corresponding to the single item grade groups, not to remove the single item grade groups themselves (to reduce duplication).

Using the `count_occurences_by_grade` example with "Grade 5" grade group added, when `remove_single` is `TRUE` we get:
```
                A           B    
              (N=3)       (N=3)  
—————————————————————————————————
-Any-       3 (100%)    3 (100%) 
Grade 1-2   1 (33.3%)   2 (66.7%)
1               0       1 (33.3%)
2           1 (33.3%)   1 (33.3%)
Grade 3-5   2 (66.7%)   1 (33.3%)
3           2 (66.7%)       0    
4               0       1 (33.3%)
Grade 5         0           0    
```

Note that "5" is excluded but "Grade 5" is present.

When `remove_single = FALSE`, we get:
```
                A           B    
              (N=3)       (N=3)  
—————————————————————————————————
-Any-       3 (100%)    3 (100%) 
Grade 1-2   1 (33.3%)   2 (66.7%)
1               0       1 (33.3%)
2           1 (33.3%)   1 (33.3%)
Grade 3-5   2 (66.7%)   1 (33.3%)
3           2 (66.7%)       0    
4               0       1 (33.3%)
5               0           0    
Grade 5         0           0    
```

Here both "5" and "Grade 5" are included, but would include identical values.

Let me know if that makes sense, I know the wording is a bit confusing!

**Comment by Melkiades** [comment]
@edelarua it works fine when substituting singles but if I add "Grade 3-5" and I want to take out 3, 4, 5, `remove_singles` does not take them out

**Comment by edelarua** [comment]
Hi @Melkiades,
That is also expected - `remove_singles` is *only* for 1-to-1 replacement (i.e. replace a single grade with a grade group containing that single grade), basically just relabelling without any loss of information. 
Since it is still useful in most cases to include the single grades in addition to the grade groups when a group contains multiple grades - as I believe is the standard in most/all tables - these rows are left in. If a user wants to only include the grade groups they specify, that would be done in pre-processing or by using a split function.

**Comment by Melkiades** [comment]
Could we also add this option by expanding the scope of remove_single? I think it would be handy, and also it was asked recently.

**Comment by edelarua** [comment]
> Could we also add this option by expanding the scope of remove_single? I think it would be handy, and also it was asked recently.

I'll add another option to remove all rows but the specified grade groups.
