### ISSUE TITLE
Investigate feasibility of exclusively using ggplot2 for all plots - part II (g_km)

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#1167]
See original issue https://github.com/insightsengineering/tern/issues/1109

Currently all but two plotting functions exclusively use ggplot2. These two functions were implemented using grobs to avoid issues when combining plots with accompanying annotation tables.

Look into feasibility of converting the following functions to use only ggplot2 (i.e. geom_text) instead of grobs:

**Comment by Melkiades** [comment]
Is this still in progress?

**Comment by shajoezhu** [comment]
hi @edelarua , was wondering how we doing on this?

@Teninq , is there anything else that you would like to request regarding this feature?

**Comment by edelarua** [comment]
I am still working on this! I can focus on finishing it up since I’m probably about halfway done.
