### ISSUE TITLE
Remove deprecated functions

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/tern#1179]
Identify functions that are due to be removed (i.e. deprecation cycle initiated in previous version) and remove them (and their tests/references) from the package. Check for any occurrences in other NEST packages prior to removal.

**Comment by shajoezhu** [comment]
Thanks @edelarua , yes, let's get started on this. but merge it in after tmc cran release, blocked by https://github.com/insightsengineering/teal.modules.clinical/issues/920
