### ISSUE TITLE
Change by default format for pvalue in analyze_vars()

### ISSUE THREAD

**Issue by imazubi** [insightsengineering/tern#1203]
### Feature description

Hi Nest team! 

We are getting the following by default format for the pvalue under _analyze_vars_
<img width="486" alt="image" src="https://github.com/insightsengineering/tern/assets/87760125/85e96205-1c04-41b4-8ae4-a3f284931256">

Could we update it so that the default format is _"x.xxxx | (<0.0001)"_? This would make more sense. 

<img width="510" alt="image" src="https://github.com/insightsengineering/tern/assets/87760125/a2aeddf6-ebce-47ee-ba43-fe1102af9bfe">

```
> packageVersion("tern")
[1] ‘0.9.3’
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by edelarua** [comment]
Thanks for bringing this to our attention Ima! This will be fixed by #1204.

**Comment by shajoezhu** [comment]
tagging @shajoezhu and @khatril for checking

**Comment by khatril** [comment]
This is fine to implement, please proceed with the MR
