### ISSUE TITLE
[Question]: typo in the "Occurrence table pruning" reference site

### ISSUE THREAD

**Issue by adcascone** [insightsengineering/tern#1265]
### What is your question?

In the example section of the "Occurrence table pruning" reference site, should this text (and the associated output) be adjusted to reflect the usage of `has_fraction_in_any_col()`?

Current:
```
# `has_fraction_in_any_col`
any_atleast_five_percent <- has_fraction_in_any_col(atleast = 0.05, col_names = names(tab))
prune_table(tab, keep_rows(more_than_five_percent))
```

Suggested adjustment:
```
# `has_fraction_in_any_col`
any_atleast_five_percent <- has_fraction_in_any_col(atleast = 0.05, col_names = names(tab))
prune_table(tab, keep_rows(any_atleast_five_percent))
```

Thank you!
Arianna C.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by edelarua** [comment]
Thanks for your question @adcascone! This is in fact a typo that I'll have corrected.

**Comment by adcascone** [comment]
Thank you!
