### ISSUE TITLE
[Question]: More information needed on summarize_glm_count()

### ISSUE THREAD

**Issue by chelseadickens** [insightsengineering/tern#1268]
### What is your question?

@adcascone and I are trying to understand where the outputs under "Unadjusted exacerbation rate (per year)" and "Adjusted (QP) exacerbation rate (per year)" from the example in [Summarize Poisson negative binomial regression](https://insightsengineering.github.io/tern/latest-tag/reference/summarize_glm_count.html) are calculated by summarize_glm_count() and associated functions (e.g., s_glm_count()). 

Which package(s)/functions is this built on, and how are these calculations done?

Is it possible to add details to the function documentation to detail this or to add a reference that contains details for the calculations? 

Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by shajoezhu** [comment]
Dear @chelseadickens , hope you are well. Could you please repost the question to the StackOverflow, and nest-tern and nest-rtables. Thanks! We will be able to track the answers there.

**Comment by adcascone** [comment]
Here is the post on StackOverflow: https://stackoverflow.com/questions/78754751/more-information-needed-on-summarize-glm-count

Thanks again!
