### ISSUE TITLE
[Bug Report] `g_km` fails with multiple max time records

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/tern#1279]
When multiple records have estimates at max time, `g_km` fails with error:

```
Error in yval == “Survival” && data$estimate[data$time == max_time2] > : length = 2’ in coercion to ‘logical(1)’
```

**Comment by shajoezhu** [comment]
hi @khatril , is this right though? can we have multiple records at t_max? 

@edelarua , when this bug was flagged, was it from a single patient? or multiple? 

Thanks

**Comment by edelarua** [comment]
Hi @shajoezhu,

I’m not 100% sure this is the issue but based on the error message returned and the context from the post I think it’s likely this. If this outcome isn’t allowed I can add an error message instead. The post is on Roche Overflow if you’d like to read it over.
