### ISSUE TITLE
Complete deprecation of arguments deprecated <0.9.4

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/tern#1303]
Complete deprecation of arguments deprecated prior to tern v0.9.4 (December 2023 or eariler)

- `control_lineplot_vars` args `strata` and `cohort_id`

**Comment by shajoezhu** [comment]
hi @edelarua , please make sure these were strictly before 0.9.4, at the most 0.9.3 changes.

we have tern.mmrm, teal.modules.clinical on cran depends on tern >= 0.9.4. thanks!

**Comment by edelarua** [comment]
Yes I've double-checked - everything was deprecated in 0.9.3 or 0.9.2 :)

**Comment by shajoezhu** [comment]
brilliant! Thanks a lot!
