### ISSUE TITLE
[Investigate if we can close this issue already] problematic survival package over >= "3.2.9" version (at least clogit)

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/tern#15]
<REDACTED>NEST/tern/pull/1277
<REDACTED>NEST/tern/issues/1275
@anajens 
Most important on BEE R 4.0.3 we use survival version '3.2.7' so this is not a problem there.
@waddella ask us to test NEST packages on R 4.1.0 with newer `survival`.

TL;DR
Precisely survival::clogit might give Inf loop over >= "3.2.9" `survival` version, only for "exact" method and presorted dataset.
If we shuffle the dataset, then it optimize correctly. So it looks like pre-sorted data might cause problems now for "exact" method.
I created a github issue https://github.com/therneau/survival/issues/151 , hopefully survival authors will respond.

The new scaling functionality was introduce with this commit https://github.com/therneau/survival/commit/cd134967a9b9cfc59e37731b88d191a6d26f4155#diff-9c3fe81a7b4cf1c186184f63ea7d06bc27fafc3707a1dcaff9896bb96036349a, which i think is the source of the problem. (here (scaling) it crashed RStudio too https://github.com/therneau/survival/issues/146). Moreover `clogit` ("exact" method) depends on `coxph` which looks to cause the problem.

In my opinion we should wait till `survival` package maintainers will solve this [issue](https://github.com/therneau/survival/issues/151).  Till this moment we could not use `survival` version >= "3.2.9". 

Another option is to use popular method "breslov" which is used in other packages. 
<REDACTED>user/2704/files/40cfec00-df09-11eb-87e8-d13398f8423b)

There was another solution suggested to always shuffling a dataset. 

Provenance: 
```
Creator: Polkas
```

**Comment by edelarua** [comment]
Resolved. We are currently using `survival version >= 3.2-13`
