### ISSUE TITLE
new ignores

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/tern#20]
linked to teal/#1073

Provenance: 
```
Creator: Polkas
```

**Comment by Melkiades** [comment]
> Hi @Polkas , I was wondering for this issue, I think we can relate to the commit in teal [insightsengineering/teal@bd414a5](https://github.com/insightsengineering/teal/commit/bd414a5b1fcf0057df4b43600ab3634ca54cb6f4)
> 
> I was wondering shall we update the tern [.Rbuildignore](https://github.com/insightsengineering/tern/blob/main/.Rbuildignore) and [.gitignore](https://github.com/insightsengineering/tern/blob/main/.gitignore) in the same fashion as [insightsengineering/teal@bd414a5](https://github.com/insightsengineering/teal/commit/bd414a5b1fcf0057df4b43600ab3634ca54cb6f4), was this what you meant before?
> 
> I wonder, if we should do a refactoring for all the ignore files and Rbuildignore across all NEST repos? We can section these artefacts by section, i.e.
> 
> ```
> # cicd
> ^\.CI-FORCE-RELEASE-VERSION$
> ^\.drone\.yml$
> ^Jenkinsfile$
> ^\.gitlab-ci\.yml$
> 
> # Design
> design/*
> 
> # doc
> ^docs$
> man-roxygen/*
> 
> # git
> ^\.github$
> README.*
> ^LICENSE\.md$
> TODO\.md
> 
> # lintr
> ^\.lintr$
> 
> # pkgdown
> ^_pkgdown\.yml$
> 
> # Rproj
> ^.*\.Rproj$
> ^\.Rproj\.user$
> 
> # staged dependencies
> ^staged_dependencies\.yaml$
> 
> # others
> ```
> 
> @dinakar29 @waddella @danielinteractive @pawelru I was wondering what do you think? We can section these headings, and sort them alphabetically, easier for navigation, and avoid duplicated efforts. Thanks!

I think ordering the ignore files like this would be nice. It can probably be done in #870. What do you think @edelarua ?

**Comment by shajoezhu** [comment]
do it~ :)
