### ISSUE TITLE
Safety reports for EU submission

### ISSUE THREAD

**Issue by yangx61** [insightsengineering/tern#237]
# Goal/Success Critieria

Create the following tables using tern/rtables so that EU access group can generate the summary using NEST. Moving from entimice/STREAM to NEST hopefully will significantly reduce the time needed to generate these results.

![image](https://user-images.githubusercontent.com/91914821/139108899-f1193761-4463-41ca-ab43-742600fb2a1c.png)

## additional information

- Full table can be found [here](https://docs.google.com/spreadsheets/d/1p3W4rTIcbGVJq909XzrDVR2UjmdduUwR/edit#gid=254767838)

- Some components similar to [FSTG02](https://docs.roche.com/doc/tlg-catalog/2021_10_13/tlg_catalog/graphs/fstg02/)

- We will start with safty-tte summary as the first pilot.

Ensure in `tern`, that the `s_*` with the summaries exists.

## Needed Data

* `ADTTE` with variables `AESOC`, `AEPT`

## Needed Summaries

* Patients
   - `n`:
   - `%`: `n/N`
* Patient with Event
   - `n`: `ADAE$abc == 'Y'`
   - `%`: `n/N`
* Censored
* Log Rank
* Hazard Ratio
   - Convergence Status: 
* Interaction Test

## Example

Tecentriq HCC as a fairly recent example

Example outputs for one data cut: `root/clinical_studies/RO5541267/CDT30091/YO40245/data_analysis/ACE_29NOV2019/prod/output`

Additional data sets (beyond core study VADs) for this data cut:
`root/clinical_studies/RO5541267/CDT30091/YO40245/data_analysis/ACE_29NOV2019/prod/outdata_vad`

programs: 
`root/clinical_studies/RO5541267/CDT30091/YO40245/data_analysis/ACE_29NOV2019/prod/program/autoexec.sas` - for the subgroup definitions

`root/clinical_studies/RO5541267/CDT30091/YO40245/data_analysis/ACE_Base/prod/program` - note use of bubble up so same analysis is run against multiple data cuts
Relevant for now is likely `data_aette.sas` and `saf_tte`.

Current tool: [HEIDI](https://sites.google.com/roche.com/heidi/home) to read in a modified STREAM results dataset summarizing all output content and then generate heatmaps etc to facilitate exploration of created results.

More information:
https://drive.google.com/drive/u/0/folders/1FLaPNwoWbE8MC80ydad8zjodiKdo11dq

**Comment by shajoezhu** [comment]
closing issue as it is no longer required
