### ISSUE TITLE
Add weighted log-rank tests

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/tern#30]
> Besides the log-rank (cox score) p-value, tern currently supports cox wald and likelihood ratio test p-values. Missing are weighted log-rank tests, e.g. Peto-Peto, Gehan-Breslow, etc.

>Currently, these tests serve as sensitivity analyses at best (not included in most SAPs). The log-rank test remains the preferred primary analysis for time-to-event endpoints by regulatory agencies. So the question comes down to how much we prioritize primary vs secondary analysis of clinical endpoints.

<REDACTED>NEST/tlg-catalog/pull/611

Provenance: 
```
Creator: anajens
```

**Comment by shajoezhu** [comment]
closing low-priority, prior 2021 December issues
