### ISSUE TITLE
Add exact logistic regression option to `fit_logistic()`.

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/tern#32]
This is required as a new option for the LGRT02 output table (multivariate logistic regression).

Unfortunately there does not seem to be a conventional implementation for it in R. The `elrm` package does not seem optimal as it uses MCMC which always comes with problems and has been removed from CRAN. A couple of code snippets can be found, e.g. see
https://zhanxw.com/blog/2011/02/exact-logistic-regression/

So this would be a quite large more research/stats effort here.

Provenance: 
```
Creator: danielinteractive
```

**Comment by shajoezhu** [comment]
closing low-priority, prior 2021 December issues
