### ISSUE TITLE
Review exported functions of tern

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/tern#334]
@shajoezhu - there are lot of exported functions in tern (more than 300!) are they all needed to be exported?

**Comment by Melkiades** [comment]
I will close this now as the number of exported functions has been reduced by PR #583. I just want to mention that there are still groups of functions not perfectly documented and that may benefit from a more precise reorganization. Similarly, issue #393 can be closed with the need for better reorganization of the reference page in the `_pkgdown.yml` file.
