### ISSUE TITLE
eu access specify the statistics

### ISSUE THREAD

**Issue by waddella** [insightsengineering/tern#336]
related to EU access task https://github.com/insightsengineering/tern/issues/237

# Todo

* list the columns in the table and define their derivation
* check in `tern` which of those numbers are already implemented in `s_*` function

# Definition of done

You are able to create a function `s_eu_access` (to be renamed) that
* well parameterized (data and arguments in)
* reuses  existing `s_*` functions in `tern`
   - this may involve running computations that get discarded

```r
s_eu_access <- function(x) {
  p1 <- s_count_abnormal_by_marked(x)
  p2 <- s_num_patients(x)

  xb <- mean(x)
   
  c(
     p1[<choose your objects>],
     p2[<choose your objects>],
     mean = xb
   )
}
```

**Comment by shajoezhu** [comment]
closing issue as it is no longer required
