### ISSUE TITLE
eu access: use rtables to get the table

### ISSUE THREAD

**Issue by waddella** [insightsengineering/tern#337]
this issue is in the context of #237 

currently `rtables` has some limitations to place `s_*` results in the colmuns, so for this step lets focus on the correct sub-setting in the rows and place the `s_eu_access` results into rows.

Note: you probably need to define custom splitting functions.

# Definition of done

Get the correct numbers with real data

**Comment by shajoezhu** [comment]
closing issue as it is no longer required
