### ISSUE TITLE
eu access: csv

### ISSUE THREAD

**Issue by waddella** [insightsengineering/tern#338]
use the `s_eu_access` to create a `data.frame` with the correct subsetting.

# Todo

* Figure our the requirements of `csv`
* this probably requires us to re-create the subsetting logic for the rows.
   * what is a good parameterization
   * trivial to parallelized (look HPC, or Ocean)

# Definition of done

* Ready to be presented to the EU-access team to get feedback

**Comment by shajoezhu** [comment]
closing issue as it is no longer required
