### ISSUE TITLE
Support multiplicity adjustment for TTET01

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/tern#36]
<REDACTED>pd/post/do-you-use-ttet01-for-time-to-event-analyses-please-read/
I guess we don't have this problem in the sense that we currently do NOT support p-value adjustment with Bonferroni. 

"Issue: For studies in which more than 2 study arms are displayed in one TTET01 table (e.g., Control, Treatment 1, Treatment 2), STREAM will by default make the Bonferroni p-value adjustment for multiplicity. STREAM v1 allowed the option to employ a separate model for each pairwise comparison (in which case no adjustment would be performed) while STREAM v2 does not allow that option.  This could result in inconsistencies in output between STREAM v1 and v2 when more than 2 study arms are displayed in one table."

But I guess it would be a nice additional feature for our t_tte if we would support the Bonferroni p-value adjustment.

Provenance: 
```
Creator: danielinteractive
```

**Comment by shajoezhu** [comment]
closing low-priority, prior 2021 December issues
