### ISSUE TITLE
Incorrect reference list in the tern pkgdown

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/tern#393]
https://bookish-invention-97673167.pages.github.io/reference/index.html#statistics-functions
The one family functions (prefix with h_, a_, s_) are duplicated across different subsections, the structure is highly misleading. 
This comes from roxygen2 `describeIn` functionality as influence the pkgdown.yaml.

It looks like there is no control for that from the perspective of pkgdown.
https://github.com/r-lib/pkgdown/issues/986

One of the solutions is to rewrite the pkgdown yaml file to assume all siblings are in the one place.
The other solution is to rewrite the roxygen2 which does not looks to be a right one.
Or `man-roxygen` ...
Or simplify the reference and leave only the analyze functions (end product)

Ps. if updating pkgdown yaml please use `- starts_with("a_")` syntax to make code more elegant and easier to maintain.

**Comment by Melkiades** [comment]
This is not in our planned increment but I think it is still valid and valuable 👍
