### ISSUE TITLE
New Tern Function: Scatter Plot (SHG01) & Scatter Plot (SLG01)

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/tern#40]
New function should be able to create the following outputs

SHG01

Scatterplot of Maximum Level of Liver Function Tests
Scatterplot of Maximum Level of Liver Function Tests including Reference Lines

[STREAM Catalog Link](https://pages.github.roche.com/MDIS/stream_doc/2_12/um/report_outputs_shg01.html?highlight=shg01)

SLG01

Scatterplot of Maximum Level of Liver Function Tests
Scatterplot of Maximum Level of Liver Function Tests (adding reference lines using the recode option)
Scatterplot of Maximum Level of Liver Function Tests (adding reference lines using a pre-processing)

[STREAM Catalog Link](https://pages.github.roche.com/MDIS/stream_doc/2_12/um/report_outputs_slg01.html?highlight=slg01)

Provenance: 
```
Creator: npaszty
```

**Comment by shajoezhu** [comment]
closing low-priority, prior 2021 December issues
