### ISSUE TITLE
New Tern Function: Liver Function Tests Patient Profile (LFG01)

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/tern#43]
New function should be able to create the following outputs

LFG01
Liver Function Tests Patient Profile (LFG01)
Liver Function Tests Patient Profile (LFG01) (wrapping patient characteristics)

[STREAM link](https://pages.github.roche.com/MDIS/stream_doc/2_12/um/report_outputs_lfg01.html?highlight=lfg01)

Provenance: 
```
Creator: npaszty
```

**Comment by shajoezhu** [comment]
closing low-priority, prior 2021 December issues
