### ISSUE TITLE
New Tern Function: Individual Patient Plot over Time with Treatment Group Mean (IPP02)

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/tern#44]
New function should be able to create the following outputs

IPP02
Individual Patient Plot over Time with Treatment Group Mean
![image](https://user-images.githubusercontent.com/91914821/140619635-2fb918bd-66f2-46ab-bbf3-356cf1d274b6.png)

Individual Patient Plot over Time with Treatment Group Mean with Attributes Unified with a Group
![image](https://user-images.githubusercontent.com/91914821/140619675-a46b52d6-37bb-46b4-a712-9cf2a6c94b7c.png)

Individual Patient Plot over Time with Treatment Group Mean and 95% CI with Attributes Unified with a Group
![image](https://user-images.githubusercontent.com/91914821/140619684-99a83697-e9ba-41d0-8ff0-1e2410972f0c.png)

<REDACTED>MDIS/stream_doc/um/report_outputs_ipp02.html)

Provenance: 
```
Creator: npaszty
```

**Comment by shajoezhu** [comment]
closing low-priority, prior 2021 December issues
