### ISSUE TITLE
Create example dataset in tern of count endpoint

### ISSUE THREAD

**Issue by brandondbutcher** [insightsengineering/tern#537]
# Motivation 

This is part of adding the new template RATET01, see https://github.com/insightsengineering/tern/issues/319

To-Do

- [ ] Create an example dataset in tern of a count endpoint with a time at risk variable
- [ ] Add additional rows to `adtte` in `scda` package for count AVAL
- [ ] Add an additional column to `adtte` in `scda` package for a new variable, `lgTMATRSK`, for the corresponding follow up time variable

**Comment by brandondbutcher** [comment]
@ayogasekaram See updated To-Do. We can chat further when we meet on Tuesday.

**Comment by shajoezhu** [comment]
Hi @brandondbutcher , thanks for updating this instruction here. Can you please create another issue at https://github.com/insightsengineering/random.cdisc.data/issues.

once the adtte is updated, there would be potential downstream break changes in tern, tmc, tlg-c and sample apps

fyi @ayogasekaram

**Comment by brandondbutcher** [comment]
Closing, see issues on random.cdisc.data: https://github.com/insightsengineering/random.cdisc.data/issues/161#issuecomment-1168167763
