### ISSUE TITLE
Implement 3 signification figures in the PKCT01

### ISSUE THREAD

**Issue by qiliu1013** [insightsengineering/tern#544]
Example: https://www.chem.fsu.edu/chemlab/chm1020c/lecture%202/04.php#:~:text=There%20are%20three%20rules%20on,decimal%20portion%20ONLY%20are%20significant.

**Comment by Melkiades** [comment]
Solved in #756 with format function _Originally posted by @gmbecker in https://github.com/insightsengineering/formatters/issues/26#issuecomment-1128153550_
