### ISSUE TITLE
Add `prop_diff_stratnc()` calculating the stratified Newcombe CI

### ISSUE THREAD

**Issue by bahatsky** [insightsengineering/tern#588]
For a study we are working on a shiny app and one of the outputs should look like below. To enable this we would need to have stratified Newcombe confidence interval (as there are strata).

see https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/procstat/procstat_freq_details63.htm and references therein for the method

To do:

- [x] design
- [x] implementation
- [x] examples
- [x] tests

**Comment by shajoezhu** [comment]
From @bahatsky , 

> https://blogs.sas.com/content/iml/2022/04/18/mcnemar-test-sas.html could be a good starting point.

**Comment by shajoezhu** [comment]
Thanks so much @danielinteractive

**Comment by Melkiades** [comment]
I am adding also `prop_strat_wilson` (with and without continuity correction) and Yan and Su (2010) heuristic which is used to estimate weights. In Daniel's design, the stratified Newcombe is calculated with weights that come from a modified CMH which now outputs the found weights. As I implemented now the heuristic, it outputs too the found weights (I might add the switcher for that in `stratnc` later. Here I add some points for me to keep track of the latest developments:

- [ ] Add directly tests for `estimate_proportion` when used with `rtables` (not related to current design, it was missing)
- [ ] Implement strat_wilson from Daniel's design
- [ ] Add heuristic for weights
- [ ] Documentation
- [ ] Examples
- [ ] Tests
- [ ] Adapt `s_proportion` to work with strata
- [ ] Adapt `estimate_proportion` to work with df and therefore strata for this specific case
- [ ] Add more tests and examples for the latter specific case (behavior with `rtables`)

**Comment by danielinteractive** [comment]
thanks @Melkiades for working on this!

**Comment by Melkiades** [comment]
Thanks to you for the great initial design! I just completed the first part (`s_proportion` and `prop_strat_wilson`). At the beginning, I took out the `suppressWarnings()` around `stats::prop.test()`, but when I added the real data test is complaining a lot about an approximation done. Do you know what is this behavior precisely?

I asked for your review of the code, and I really tried my best to make `s_proportion` fit the new structure but I am sure there is space for improvement there as I took inspiration from `prop_diff` directly. Any suggestion is super welcome!

Note: it is still missing the stratified Newcombe. I will work on that tomorrow ;)

**Comment by danielinteractive** [comment]
Thanks @Melkiades - yeah we should suppress those warnings as we are not interested in them here. Due to the stratification there is small numbers everywhere, but the method is as it is, so it is supposed to use the small numbers.
