### ISSUE TITLE
Remove `assertthat` dependency and use `checkmate` instead

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/tern#597]
### Feature description

There is no point in importing two assertions packages. Let's use one throughout the codebase. My recommendation is `checkmate`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
I fully agree with using only `checkmate` as you can see from this table of use. `checkmate` has more functions and users, and it is still under active development and maintenance.
![Screenshot 2022-06-20 141700](https://user-images.githubusercontent.com/11279768/174600113-da3f6dfc-a495-4acb-a4dc-05e614e6a9aa.png)

**Comment by Melkiades** [comment]
Can I proceed with this @shajoezhu? At the moment there are 385 functions that depend on `assertthat` and 60 that depend on `checkmate`, but for what I posted in the previous comment, I think it is better to keep only the latter.

**Comment by pawelru** [comment]
Unfortunately I have to re-open this as not fully completed. `assertthat` package is still there in the DESCRIPTION file. The goal is to have one dependency on the assertions package.
