### ISSUE TITLE
Remove deprecated mmrm functions from `tern` package

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tern#621]
Motivation: Since there was one release at least with the functions deprecated, I think now it would be a good time to remove them.

To do:

Remove all of 
- [x] fit_mmrm
- [x] g_mmrm_diagnostic
- [x] g_mmrm_lsmeans 
- [x] h_mmrm_cov
- [x] h_mmrm_diagnostic
- [x] h_mmrm_fixed
- [x] s_mmrm_lsmeans
- [x] s_mmrm_lsmeans_single
- [x] summarize_lsmeans

**Comment by danielinteractive** [comment]
@shajoezhu would be cool if SME team could do this, thanks

**Comment by Melkiades** [comment]
at the moment the deprecated files are the following.
- [ ] `deprec-fit_mmrm.R` 
- [ ] `deprec-g_mmrm.R`
- [ ] `deprec-tabulate_mmrm.R`
`deprec-nest_colors.R`  is from this increment so it should be removed after the next release. The other files should be removed (I think many of the functions specified by @danielinteractive are in these files). From the list, you provided many of the `tabulate_mmrm` functions are missing. Should I write them all extensively and then remove them (with proper downstream checks ofc) @shajoezhu ?

**Comment by Melkiades** [comment]
This is also generating a lot of confusion in the TLG catalog as there is heavy masking that can lead to unwanted behaviors:
  ```
  The following objects are masked from 'package:tern':
    
        fit_mmrm, g_mmrm_diagnostic, g_mmrm_lsmeans, h_mmrm_cov,
        h_mmrm_diagnostic, h_mmrm_fixed, s_mmrm_lsmeans,
        s_mmrm_lsmeans_single, summarize_lsmeans
    
```
