### ISSUE TITLE
Removal of non-standard folders `design` and `man.roxygen`

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#626]
I am not fully sure about the scope of these two folders, but they might not be actually useful beyond development. The first `design` may also contain sensitive information as it seems constituted of skeletons and trials of past tlgs. About the second folder, I am not fully aware of its purpose, but there might be a better way to add authors. 

Any feedback about this is welcome @gogonzo @shajoezhu 

NB: this might be relevant for `--as-cran` checks as non-standard folders and files should be avoided.

**Comment by gogonzo** [comment]
I'm don't have a strong opinion about the `design` it just seemed bad for me from the day one I saw it. `man-roxygen` is useful as it holds some roxygen templates (but authors template doesn't make so much sense as it's just one-liner).

`man-roxygen` should be added to `.Rbuildignore`.

**Comment by shajoezhu** [comment]
close as its done. Moved to internal design repo

**Comment by Melkiades** [comment]
> I still think we should take out `man.roxygen/` as it is not updated since years and I am sure there are better ways to keep track of that information

will be closed by #870
