### ISSUE TITLE
revisit the assert logic in `h_adlb_worsen` and `fit_single_optimizer`

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#628]
# motivation

Recent changes in `assert_that` is breaking downstream tlg-c, please revisit the assert logic

- [x] error 1 --> `lbt08.Rmd`

```
Error in h_adlb_worsen(adlb, worst_flag_low = c(WGRLOFL = "Y"), worst_flag_high = c(WGRHIFL = "Y"),  : 
      Assertion on 'unique(adlb[[direction_var]])' failed: Must be a subset of {'B','L','H'}, but has different type.
```

- [x] error 2 --> `mmrmt01.Rmd`

```
fit_single_optimizer(formula = formula, data = data, reml = reml,  : 
      length of 'dimnames' [1] not equal to array
```

See https://code.roche.com/nest/docs/tlg-catalog/devel/-/jobs/9944535 for more details

**Comment by Melkiades** [comment]
So the second error comes from [mmrm#L29](https://github.com/openpharma/mmrm/blob/d61c166e2e0f8ee9aa6ca009d3babdaef3dd91f8/R/fit.R#L29). I will try to fix this but I think it is due to the TLG itself and not the assertion

**Comment by Melkiades** [comment]
So the second error is very hard to pinpoint, but it boils down to these lines of code from `h_mmrm_tmb_fit`: 
 ```
  tmb_report <- tmb_object$report(par = tmb_opt$par)
  x_matrix_cols <- colnames(tmb_data$x_matrix)
  visit_names <- levels(data[[formula_parts$visit_var]])
  cov <- tcrossprod(tmb_report$covariance_lower_chol)
  dimnames(cov) <- list(visit_names, visit_names)
```

In particular, `str(cov)` is `num [1:5, 1:5]` , while `str(list(visit_names, visit_names))` is `List of 2 $ : chr [1:6] $ : chr [1:6]`, hence the mismatched dimensions and the error. This error has probably nothing to do with recent assertion changes in tern. The code is very involuted and there are many function calls. I will attempt to find the culprit (if the TLG `mmrmt01` or a bug in `mmrm`), but I think @danielinteractive can help in fixing this.

**Comment by Melkiades** [comment]
Of course! This is from `mmrmt01.Rmd`:
```
library(dplyr)
library(tern.mmrm)
library(scda)
library(broom)

adsl <- synthetic_cdisc_data("latest")$adsl
adqs <- synthetic_cdisc_data("latest")$adqs

# Ensure character variables are converted to factors and empty strings and NAs are explicit missing levels.
# For details, refer to Teal and Study Data article.
adsl <- df_explicit_na(adsl)
adqs <- df_explicit_na(adqs)

adqs_f <- adqs %>%
  dplyr::filter(PARAMCD == "FKSI-FWB" & !AVISIT %in% c("BASELINE")) %>%
  droplevels() %>%
  dplyr::mutate(ARMCD = factor(ARMCD, levels = c("ARM B", "ARM A", "ARM C"))) %>%
  dplyr::mutate(
    AVISITN = rank(AVISITN) %>%
      as.factor() %>%
      as.numeric() %>%
      as.factor()
  )
adsl_sub <- adqs_f %>%
  dplyr::filter(!is.na(CHG)) %>%
  distinct(USUBJID) %>%
  left_join(adsl, by = "USUBJID")
var_labels(adqs_f) <- var_labels(adqs)
# here it throws the error
mmrm_results <- fit_mmrm(
  vars = list(
    response = "CHG",
    covariates = c("BASE", "STRATA1", "BMRKR2"),
    id = "USUBJID",
    arm = "ARMCD",
    visit = "AVISIT"
  ),
  data = adqs_f,
  cor_struct = "unstructured",
  weights_emmeans = "equal",
  optimizer = "automatic"
)
```
My intuition says that it might be due to the `SCREENING` level from the `AVISIT` column. Now that I think about this, I think the error resides in this: `synthetic_cdisc_data("latest")$adqs`

**Comment by Melkiades** [comment]
So basically the formula is the following:
```
$formula
CHG ~ BASE + STRATA1 + BMRKR2 + ARMCD * AVISIT + us(AVISIT | 
    USUBJID)
```
and these are the levels of `AVISIT`:
```
attr(,"label")
        AVISIT 
Analysis Visit 
Levels: SCREENING WEEK 1 DAY 8 WEEK 2 DAY 15 WEEK 3 DAY 22 WEEK 4 DAY 29 WEEK 5 DAY 36
```

**Comment by Melkiades** [comment]
The hotfix does not work as I expected. So it is more a problem of `mmrm`. I will create a PR there.

**Comment by danielinteractive** [comment]
thanks @Melkiades , I created an issue already in `mmrm` so you could propose to close that with your PR
