### ISSUE TITLE
[Feature Request]: obtain pvalue of the mean

### ISSUE THREAD

**Issue by imazubi** [insightsengineering/tern#638]
### Feature description

Hi my NEST friends! 

Currently I am not seeing any function where I can obtain the p-value of the change from baseline (or even of the AVAL mean value) to test whether it is statistically significant from 0 (or other mean value to be tested under the null hypothesis). 
![image](https://user-images.githubusercontent.com/87760125/178442035-096c6098-3c16-4b01-84eb-47e0dbc6d48f.png)

In the `summarize_change()` function we are able to get the CI of the mean but sometimes the p-value is also desired. 

By looking at the [stat_mean_ci](https://github.com/insightsengineering/tern/blob/main/R/stat.R#L108) function, we could create another similar function i.e `stat_mean_pvalue`. See a fast draft of the function design. 

```
stat_mean_pv <- function(x,
                         na.rm = TRUE, 
                         n_min = 3L, 
                         diff_test = 0L
) {
  if (na.rm) {
    x <- stats::na.omit(x)
  }
  n <- length(x)
  x_mean <- mean(x)
  x_sd <- sd(x)
  if (n < n_min) {
    pv <- c(p_value = NA_real_)
  } else {
    #two sided pvalue
    x_se <- sd(x) / sqrt(n)
    ttest <- (x_mean - diff_test) / x_se
    pv <- c(p_value = 2 * pt(-abs(ttest), df = n - 1))
  }
}

return(pv)
}
```

Then by enhancing the `summary_formats, summary_labels, summarize_vars, summarize_change`, and by creating a similar helper function such as `f_conf_level` (to add in the stats label of the final table which is the mean value to be tested under the null hypothesis) the desired output would be achieved. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by dinakar29** [comment]
Hi @imazubi! I'm tagging @shajoezhu here for visibility. We'll look into this.

**Comment by shajoezhu** [comment]
Thanks @dinakar29 for the tagging!

hey @imazubi , long time no see man! Thanks for the design document. We will look into this piece
