### ISSUE TITLE
[Bug]: summarise_vars cannot handle character variables which are not present in both arms

### ISSUE THREAD

**Issue by kieranjmartin** [insightsengineering/tern#650]
### What happened?

If you provide a character variable without convering it to factor first, and it doesn't have a value for one arm, you get an error:

```
source("https://raw.github.roche.com/NEST/nest_on_bee/master/bee_nest_utils.R")
bee_use_nest("2022_06_09")

library(tern)
library(dplyr)


mydata <- tibble(
  ARM = sample(c("A", "B"), 50, replace = TRUE),
  RACE = sample(c('WHITE', 'ASIAN', 'AMERICAN INDIAN OR ALASKA NATIVE', 
                  'UNKNOWN', 'MULTIPLE',
                  'BLACK OR AFRICAN AMERICAN'
                  ), 50, replace = TRUE))

mydata$RACE[1] <- "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER"  
#mydata$RACE <- factor(mydata$RACE)    

vars <- c("RACE")
var_labels <- c(
  "Race"
)
result <- basic_table() %>%
  split_cols_by(var = "ARM") %>%
  add_overall_col("All Patients") %>%
  add_colcounts() %>%
  summarize_vars(
    vars = vars,
    var_labels = var_labels
  ) %>%
  build_table(mydata)
```
If you uncomment the factor conversion, this then works

### sessionInfo()

```R
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.2      tern_0.7.8       rtables_0.5.1.2  formatters_0.3.1 magrittr_1.5    
[6] reticulate_1.22 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        pillar_1.4.6      compiler_4.0.3    tools_4.0.3       digest_0.6.27    
 [6] jsonlite_1.7.1    lifecycle_1.0.1   tibble_3.0.4      gtable_0.3.0      checkmate_2.1.0  
[11] lattice_0.20-41   pkgconfig_2.0.3   png_0.1-7         rlang_0.4.11      Matrix_1.2-18    
[16] cli_2.1.0         rstudioapi_0.11   generics_0.1.0    vctrs_0.3.4       grid_4.0.3       
[21] tidyselect_1.1.0  glue_1.4.2        R6_2.5.0          fansi_0.4.1       survival_3.2-13  
[26] ggplot2_3.3.2     purrr_0.3.4       tidyr_1.1.2       scales_1.1.1      backports_1.1.10 
[31] ellipsis_0.3.1    htmltools_0.5.1.1 splines_4.0.3     assertthat_0.2.1  colorspace_1.4-1 
[36] munsell_0.5.0     broom_0.7.9       crayon_1.3.4
```

### Relevant log output

```R
Error in .make_tablerows(df, func = analysis_fun(spl), defrowlabs = defrlabel,  : 
  length(unqlens) == 1 || (0 %in% unqlens && length(unqlens) ==  .... is not TRUE
In addition: Warning messages:
1: In as_factor_keep_attributes(x, x_name = .var, na_level = na_level) :
  automatically converting character variable RACE to factor, better manually convert to factor to avoid failures
2: In as_factor_keep_attributes(x, x_name = .var, na_level = na_level) :
  automatically converting character variable RACE to factor, better manually convert to factor to avoid failures
3: In as_factor_keep_attributes(x, x_name = .var, na_level = na_level) :
  automatically converting character variable RACE to factor, better manually convert to factor to avoid failures
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
Could you provide a more specific test? if you try newer versions of tern it specifies better that you need a factor for `summarize_vars`. In the version on bee it is a bit more obscure but you need a column of factors there. It is true that the doc (`?summarize_vars`) writes the following for `var`: `vars | (character) variable names for the primary analysis variable to be iterated over.` but it refers to the column input and not the kind of values you provide in that column.

**Comment by kieranjmartin** [comment]
@Melkiades I spoke about this to @shajoezhu just now, but the basic idea is that the function warns me to convert to factor, but does not error; this implies that I am allowed to not do factor conversion first (and in general, if all I'm going to do is do "factor(variable)" it's kind of annoying that the function can't do that for me without complaint).

So the function can usually handle character inputs, although it does complain: this works:

```
mydata <- tibble(
  ARM = sample(c("A", "B"), 50, replace = TRUE),
  RACE = sample(c('WHITE', 'ASIAN', 'AMERICAN INDIAN OR ALASKA NATIVE', 
                  'UNKNOWN', 'MULTIPLE',
                  'BLACK OR AFRICAN AMERICAN'
                  ), 50, replace = TRUE))

vars <- c("RACE")
var_labels <- c(
  "Race"
)
result <- basic_table() %>%
  split_cols_by(var = "ARM") %>%
  add_overall_col("All Patients") %>%
  add_colcounts() %>%
  summarize_vars(
    vars = vars,
    var_labels = var_labels
  ) %>%
  build_table(mydata)
```

and this works 

```
mydata <- tibble(
  ARM = sample(c("A", "B"), 50, replace = TRUE),
  RACE = sample(c('WHITE', 'ASIAN', 'AMERICAN INDIAN OR ALASKA NATIVE', 
                  'UNKNOWN', 'MULTIPLE',
                  'BLACK OR AFRICAN AMERICAN'
                  ), 50, replace = TRUE))
mydata$RACE[1] <- "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER"  
mydata$RACE <- factor(mydata$RACE)    
vars <- c("RACE")
var_labels <- c(
  "Race"
)
result <- basic_table() %>%
  split_cols_by(var = "ARM") %>%
  add_overall_col("All Patients") %>%
  add_colcounts() %>%
  summarize_vars(
    vars = vars,
    var_labels = var_labels
  ) %>%
  build_table(mydata)
```

But my original example does not. I think either

a) the function does not allow character inputs at all, and errors
b) the function should handle this use case

**Comment by Melkiades** [comment]
So @kieranjmartin, I studied the issue and the problem is that a) is an unviable option due to the fact that it would reduce functionality and it would break a lot of code downstream as it is a common scenario. I tried to find a way to correct the code as you suggested in option b) but I could not manage to have the summary function see both arms and when the values are cast to factor, one arm has a different number of levels in comparison to the other arm. Here, it is `rtables` that fails to merge the two as they do not match in levels. Now, the more recent versions of `rtables` have a quite informative error message (pasted below), so I argue that this is a special case that is handled correctly and it is not necessary to force a solution as drastic as a), while b) is informative enough to understand what is going on in this specific and uncommon case.
```
> result %>% build_table(mydata)
Error: Error applying analysis function (var - RACE): Number of rows generated by analysis function do not match across all columns. 
Perhaps convert analysis variable RACE to a factor?
	occured at (row) path: root
In addition: Warning messages:
1: In as_factor_keep_attributes(x, x_name = .var, na_level = na_level,  :
  automatically converting character variable RACE to factor, better manually convert to factor to avoid failures
2: In as_factor_keep_attributes(x, x_name = .var, na_level = na_level,  :
  automatically converting character variable RACE to factor, better manually convert to factor to avoid failures
3: In as_factor_keep_attributes(x, x_name = .var, na_level = na_level,  :
  automatically converting character variable RACE to factor, better manually convert to factor to avoid failures
```

**Comment by kieranjmartin** [comment]
Thanks, I think the nice error suggestion is better

**Comment by hxfjoshua** [comment]
Hi @kieranjmartin Kieran and @Melkiades Davide, 

I recently have the exactly the same problem. I'm creating t_dm table for an early phase study. At first this study only has 1 cohort, so everything works fine. Now, we got a second cohort. At beginning I didn't convert the character variable to factor, and some values are in one arm but not in the other. I got the same error as Kieran did.

I tried to convert each character variable into factor (which is really a tedious work), different error popped up. Because in one of my variable, there are missing values. That missing value was not a problem when I only have one cohort.
`Error: NA in x has not been conveyed to na_level, please use explicit factor levels.`

Could you please advice how to address this problem? Thank you vey much.

I'm using R 4.0.4 and NEST release on 2022_01_28.

Thanks a lot.

Xuefeng Hou

**Comment by Melkiades** [comment]
Thanks for reporting this. Can I ask you the tern version (`sessionInfo()`) and a minimal test case as @kieranjmartin did? Also, I suggest you to open a new issue and ping me there, as your problem seems related to NA values and not character-factor casting.
