### ISSUE TITLE
Upgrade `testthat` to use 3rd edition

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/tern#656]
From https://github.com/insightsengineering/coredev-tasks/issues/154

Part of https://github.com/insightsengineering/NEST-roadmap/issues/65

**Comment by Melkiades** [comment]
I think we already do this right @nikolas-burkoff ?

**Comment by nikolas-burkoff** [comment]
We have if the DESC file has  `Config/testthat/edition: 3` in https://testthat.r-lib.org/articles/third-edition.html#activating

**Comment by Melkiades** [comment]
I think it is worth it. Error messages with waldo are much more informative and warnings are better handled. Is testthat at version >3 on our platforms @arkadiuszbeer ? If so I suggest to complete this

**Comment by arkadiuszbeer** [comment]
@Melkiades yes, we are using `testthat@3.1.4`

**Comment by Melkiades** [comment]
I was wondering what should we do in case of warnings. ATM it does return the warning and not the output. For example:
```
>   # Check with LOW abnormality.
>   result <- testthat::expect_warning(
+     s_count_abnormal_by_baseline(
+       df = df,
+       .var = "myrange",
+       abnormal = "LOW",
+       variables = list(id = "myid", baseline = "mybase")
+     )
+   ) %>% suppressWarnings()
> result
<simpleWarning in as_factor_keep_attributes(df[[.var]], na_level = na_level): automatically converting character variable df[[.var]] to factor, better manually convert to factor to avoid failures>
```
Should I make a wrapper of expect_warning like custom_expect_warning that preserves the old behavior with a double call or checking the piece twice in the test itself? I do not see other solutions

**Comment by Melkiades** [comment]
btw there are hundreds of errors :D
