### ISSUE TITLE
[Feature Request]: Adding a `mean_se` statistic for `summarize_vars()`

### ISSUE THREAD

**Issue by juliadedic1** [insightsengineering/tern#665]
### Feature description

Currently there is only a `mean_sd` option that can be used inside the .stats argument for `summarize_vars()`. This displays the mean and the standard deviation in brackets. For the proposed `mean_se`, we would need the mean and then the standard error in brackets. 

Motivation: This is commonly required in Ophthalmology studies and is currently needed to help produce outputs for an upcoming SREP.

Thank you! 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by danielinteractive** [comment]
thx @juliadedic1 , as discussed I think providing a PR for tern here is the quickest solution + helps to make tern even better :-)
