### ISSUE TITLE
[Feature Request]: g_lineplot work under already processed data

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/tern#689]
### Feature description

There is a feature request for our tern plot functions to work with already summarized data.
I understand it as an option to provide the `df_stats` variable as the function argument and then the raw dataset is not needed.

Example for g_lineplot:
https://github.com/insightsengineering/tern/blob/a4ad5e8a9db67042bbfb6f8e6085fec67936410b/R/g_lineplot.R#L214-L229

Please follow up the end user @gathanei

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
I checked, and adding this would complicate the code a lot as the initial data is referenced in multiple parts of the code. If a custom pre-proc function is needed, I would suggest copying and modifying the function locally. Closing this for now. We can get back to it when we get more users needing this, then we can regroup the code and make the data references more localized
