### ISSUE TITLE
Compare results for `prop_strat_wilson` with SAS and not only current results

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#697]
_Originally posted by @danielinteractive in https://github.com/insightsengineering/tern/pull/696#discussion_r964548065_

**Comment by danielinteractive** [comment]
probably still best to do that as part of the PR and not as separate task

**Comment by Melkiades** [comment]
Ideally yes, but it is already a large branch and I need a bit more time to study how to get the relevant values from SAS

**Comment by shajoezhu** [comment]
See SAS example at https://code.roche.com/nest/docs/package-designs/tern_design/-/blob/master/design/design_stratified_newcombe.Rmd#comparison-with-sas
