### ISSUE TITLE
Adding `Rdpack` for clean Bibtex citation formatting and resolve the spelling problems derived

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#702]
The issue was described briefly here ([spelling#68](https://github.com/ropensci/spelling/issues/68)) with a simple workaround, but we need to replace the code backticks with `Rdpack` that is meant to provide correctly formatted citations and references. Original discussion appears in [tern#PR696](https://github.com/insightsengineering/tern/pull/696#discussion_r966899667_). If @cicdguy and @shajoezhu agree, we can proceed with this.

**Comment by cicdguy** [comment]
No problem for me. Rdpack seems like a clean solution in general.

**Comment by shajoezhu** [comment]
We have an old issue on this https://github.com/insightsengineering/tern/issues/56

let’s reinstate rdpack :)

**Comment by cicdguy** [comment]
`Rdpack` has also been officially validated, so it's definitely in the clear for general use.
