### ISSUE TITLE
Solution for data and library loading in `testthat` 

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#703]
At the moment data from `scda` is loaded multiple times (~9.9Mb of data each time) and libraries that are only suggested by `tern` are loaded multiple times at the beginning of each long test file. I strongly suggest following this [post](https://blog.r-hub.io/2020/11/18/testthat-utility-belt/) and the issue I filed in [rtables#393](https://github.com/Roche/rtables/issues/393). In other words, I think the best way to go here is to update the setup file in `testthat/` with the libraries needed across tests and add a helper file with data loading (always in `testthat/`) so they are both done once before tests are run. This would cut down test time and useless complexity and repetition across tests. Also, we need to consider if we should be using `withr`, but this is related to a later stage imo, when we have a more reasonable data caching design (as discussed [here](https://github.com/insightsengineering/scda/issues/98)). A tentative list of things to do here:

- [ ] Adding in setup libraries and polishing loads across tests.
- [ ] Create a helper file and centralize/polish the data used in tests (only `scda`-based ones).
- [ ] Discuss a new data design following [this](https://github.com/insightsengineering/scda/issues/98) and possibly `withr`.

What do you think @cicdguy @shajoezhu ?

**Comment by cicdguy** [comment]
Based on the blog you mentioned,

* You should never touch `tests/testthat.R`
* R scripts under `tests/testthat/` whose name starts with `setup` are loaded before tests are run

I think these are novel approaches to prevent repetitive data loading and therefore improve test performance. 
So `tests/testthat/setup-data.R` would look something like this?
```
library(scda)
library(scda.2022)
scda::load_data("some data")
```

**Comment by Melkiades** [comment]
Exactly. I also changed `testthat.R` in _Rtables_ to reflect the "do-not-touch" policy. I think adding `setup-libraries.R` and `setup-data.R` is a possible nice solution to repetitions and too many mods to be made.

**Comment by nikolas-burkoff** [comment]
Need to be careful though as `test_data` will be shared by all tests so if something changes it you could be in a world of pain.

You may want to have 

```

load_data <- function(date) {
  scda::synthetic_cdisc_data(date) 
}

memoise_load_data <- memoise::memoise(load_test_data)

```
