### ISSUE TITLE
NOTE in checks: Namespace in Imports field not imported from `nestcolor`

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#705]
```
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘nestcolor’
  All declared Imports should be used.
```

I get the above note in the pipeline checks. It could be a small fix. Just pointing it out for @edelarua and @cicdguy :)

**Comment by cicdguy** [comment]
Noted. This is indeed a small fix and will need to be cleaned up. Running `R -s-e "roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace'))"` should automagically clean it up, I think.
