### ISSUE TITLE
`wrap_text` overlaps with other work

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#716]
By chance, I noticed there is a function in `wrap_text.R` that is no longer used anywhere. I was wondering if it still makes sense to have it and/or if we should adapt/move it somewhere else. I think conceptually it is more appropriate to be a function in `formatters`, where I am working on a similar implementation (unaware of the above file) here: [PR#46](https://github.com/insightsengineering/formatters/pull/46).

The author is @waddella. Any suggestion on how to proceed @gmbecker @shajoezhu @waddella? 

I am checking downstream dependencies now. For me, it is fine also to keep it as it is. I was just wondering about the possible duplication with `formatters`'function.

I could not find any downstream dep that uses this function (also, it was rendered internal and nothing broke).

**Comment by Melkiades** [comment]
I suggest adding the deprecated badge and removing it in the next increment.

**Comment by shajoezhu** [comment]
let's do that. I wil follow up with Adrian and Gabe tonight on this as well

**Comment by shajoezhu** [comment]
let's do that. I wil follow up with Adrian and Gabe tonight on this as well
