### ISSUE TITLE
Creating additional test to improve converage for rate01 related functions

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#742]
Great job Abi!! :) I did not review it in detail, as Joe is on it, but maybe we could aim at a bit higher coverage (>90%)

_Originally posted by @Melkiades in https://github.com/insightsengineering/tern/issues/739#issuecomment-1310046397_

**Comment by Melkiades** [comment]
This is blocked by current implementation of new analysis feature @ayogasekaram

**Comment by Melkiades** [comment]
I add here the reference to the dev issue (negative binomial is still missing tests right?) https://github.com/insightsengineering/sme-tasks/issues/401
