### ISSUE TITLE
NOTE on checks: missing `h_glm_negbin`

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#744]
I think the following function was present in the design file but it is missing in `tern`: 
```
h_glm_count: no visible global function definition for ‘h_glm_negbin’
Undefined global functions or variables:
  h_glm_negbin
```

ps: CRAN does not accepts notes, right? Also, I think this is related possibly with the coverage problem #742

**Comment by Melkiades** [comment]
@ayogasekaram could you investigate if this part is actually missing or not transferred from the experimental `design` file?

**Comment by ayogasekaram** [comment]
@Melkiades From my conversation with Brandon, negative binomial was partially designed but intentionally left out of summarize_glm_count.R. 
re: 
![image](https://user-images.githubusercontent.com/73252787/201738997-df120f5c-3739-42aa-af3f-9ec7c0d9e808.png)

What we can do is remove the distribution selection from the code and that may increase the test coverage.

**Comment by shajoezhu** [comment]
hey guys @ayogasekaram @Melkiades 

let's not commit for this piece for now. Given the error message, I suggest that we take out `h_glm_negbin` and close this issue for now. Thanks

**Comment by Melkiades** [comment]
I agree with @shajoezhu of course! I would keep the structure and add a stop flag for the case that is selected. So we can also test it and have high coverage.

**Comment by shajoezhu** [comment]
this is done right? @Melkiades @ayogasekaram

**Comment by ayogasekaram** [comment]
@shajoezhu I've updated the code so there's a warning when negbin is selected. I believe we discussed if there's a need/use case for the negbin design, we can add that in then. So yes, it is done
