### ISSUE TITLE
Merging setup files

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#752]
I had to load recently the setup files for tests manually and I found the fact that libraries file is only two lines a bit cumbersome to load in. I would like to suggest (I know it was me that implemented it in the first place) merging the two files and calling them just `setup.R`. Practically it does not change a  lot and I think it is a bit clearer. What do you think @cicdguy ?

**Comment by shajoezhu** [comment]
Hi @Melkiades , let's put this issue on hold please. @pawelru and I had a chat about rework on splitting the tern tests framework. We will revisit this in the next increment.

**Comment by Melkiades** [comment]
Done by @edelarua (https://github.com/insightsengineering/tern/blob/main/tests/testthat/setup.R)
