### ISSUE TITLE
Explicitly connect functions with their `rtables` counterpart

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#770]
As many issues are arising from the fact that sometimes the `summarize_*` functions in `tern` use `analyze*` functions from `rtables` mess up pagination and exports, I want to propose here to add a note in the documentation to declare which analysis function is used under the hood. Also, if many parameters are imported from `rtables`, we should add a `@seealso` specifying the main function in `rtables`. For the moment, I saw the following functions that are called `summarize` even if they use analyze:

- [ ] `summarize_colvars`
- [ ] `summarize_vars`

**Comment by Melkiades** [comment]
This can be very helpful to find other problematic functions for the same reasons. For example `summarize_patients_events_in_cols` uses `summarize_row_groups` after a split in cols which is not how it is supposed to work. This will surely fail pagination

**Comment by shajoezhu** [comment]
this is quite an issue for some time. something I consider to rewrite/rename when we refact tern. for the sake of pagination, i think we need to really reduce the usage of summerize

**Comment by gmbecker** [comment]
When this rewrite happens, I think its a good idea that each top level tern layouting function document what bare rtables layout directives it is equivalent to.

This will help people who are starting from tern functions but need custom behavior not provided by them.

**Comment by Melkiades** [comment]
@edelarua maybe this can be completed now, after last PR
