### ISSUE TITLE
Update table (and all) tests to check also correct indentation 

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#784]
> Update tests to check also correct indentation (cmt01 for example differs from others as the specific values are right indented by 1 space).
The following tables for example have different indentations than others of the same kind (see original PR for the full list). These need to be properly checked.

- [ ] cmt01 (indentation is shifted to the right in second split -> different from other tables, to check)
- [ ] aet06 (shifted indentation as in cmt01 but only for variant 1. Variant 3 and 5 have normal indentation)

_Originally posted by @Melkiades in https://github.com/insightsengineering/tern/pull/776_

Examples of different (untested) behavior (from cmt01). The first is current while the second is the one that the majority of tables have.
![Screenshot 2022-12-20 181039](https://user-images.githubusercontent.com/11279768/208898622-46880c91-8dc7-4585-ab50-16b3c9235bc9.png)
![Screenshot 2022-12-20 181108](https://user-images.githubusercontent.com/11279768/208898642-35ab8fab-3071-4a4e-9534-547fdadabfea.png)

@shajoezhu fyi

**Comment by Melkiades** [comment]
It is also possible for this to use `testthat::expect_snapshot()` as chevron team is doing atm. `vignette("snapshotting")` is a good starting point to see how it works. I honestly think it is still better to have it in a fixed form as we do now but if we do the step up to testthat 3rd edition (https://github.com/insightsengineering/tern/issues/656) we might consider this.

Incidentally in #776, I added a small utility to `to_string_matrix` that prints to console a stringed version of the result matrix to compare. This would make this issue much faster to complete

**Comment by Melkiades** [comment]
I think snapshots are our best and cleanest solution for now. I was checking how chevron does the testing here in particular (https://github.com/insightsengineering/chevron/pull/324/files#top) and we should follow suit with snapshots instead of the current copy-paste method.

**Comment by edelarua** [comment]
@Melkiades I agree that implementing snapshots is a much cleaner solution than the current template testing setup. 

@shajoezhu can we implement this solution (snapshots in tests)? It would make updating tests after changes in `tern` much quicker and easier. It should also be simple enough to migrate the tests with snapshots once we are ready to do so.
