### ISSUE TITLE
Fix format processing and resolve warnings

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/tern#788]
### Feature description

Revert default formatting for `count_fraction`s to `NULL` and apply custom formatting in analysis functions instead. Update tests accordingly.

This will fix errors occurring in several ADAT templates in TLG-C.

Also remove deprecated `size` argument and `aes_string` function from `ggplot2` to fix warnings in all `tern` tests.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by shajoezhu** [comment]
i see. Thanks @edelarua ! I was wondering does that meaning we will need to explicity set the format in chevron now?

**Comment by edelarua** [comment]
@shajoezhu it shouldn’t change anything in chevron. The problem was that the format overrode the defaults set in the analysis functions so if a different statistic was specified in `.stats` the default `.formats` value would be overridden and cause an error (e.g. `“count”` which is used in several TLG-C templates). This correction will allow the default format to be set for all statistics instead of only for `count_fraction`.

**Comment by shajoezhu** [comment]
beautiful! thanks a lot @edelarua . i already approved the PR. thanks for the changes
