### ISSUE TITLE
[Feature Request]: new tlg template

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#797]
### Feature description

in 2022, FDA provided guidance on covariate adjusted analysis, and after internal investigation, we decided to add a new output, "Summary of Marginal Effect based on Logistic Regression Model", which summarize the marginal treatment effect using G-computation, with robust sandwich estimator. The output looks like

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-f9929df6-7fff-7c5e-1a37-12dd4458ffa7"><p dir="ltr" style="line-height:1.2;margin-top:2.5pt;margin-bottom:2.5pt;"><span style="font-size:8pt;font-family:'SAS Monospace';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Summary of Marginal Effect based on Logistic Regression Model using G-Computation for &lt;Endpoint at Week X&gt;:&nbsp; &lt;Specify Population&gt;</span><span style="font-size:8pt;font-family:'SAS Monospace';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:8pt;font-family:'SAS Monospace';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Protocol: xxnnnnn</span><span style="font-size:8pt;font-family:'SAS Monospace';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /><br /></span></p><div dir="ltr" style="margin-left:0pt;" align="left">

  | Parameter Estimate | SE<(Huber-White)> | 95% CI<(Huber-White)> | xx% CI<(Huber-White)>
-- | -- | -- | -- | --
N = XXX |   |   |   |  
Proportions |   |   |   |  
\<Treatment Group \>, n = XXX | X.XXX | X.XXX | X.XXX | X.XXX
\<Control Group \>, n = XXX | X.XXX | X.XXX | X.XXX | X.XXX
  |   |   |   |  
Difference of proportions (reference= \<Control Group\>, n = XXX) |   |   |   |  
  |   |   |   |  
\<Treatment Group \>, n = XXX | X.XXX | X.XXX | X.XX – X.XX | X.XXXX
  |   |   |   |  
Ratio of proportions (reference= \<Control Group\> |   |   |   |  
Treatment Effect (reference= \<Control Group\>, n = XXX) |   |   |   |  
\<Treatment Group \>, n = XXX | X.XXX | X.XXX | X.XX – X.XX | X.XXXX
Odds ratio (reference= \<Control Group\>, n = XXX) |   |   |   |  
\<Treatment Group \>, n = XXX | X.XXX | X.XXX | X.XX – X.XX2 | X.XXXX2
  |   |   |   |  

</div><p dir="ltr" style="line-height:1.2;margin-left: 1.45pt;margin-top:2pt;margin-bottom:0pt;"><span style="font-size:8pt;font-family:'SAS Monospace';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Model contains covariates: &lt;Covariate A&gt;, &lt;Covariate B&gt;, etc.&nbsp;</span></p></b><br class="Apple-interchange-newline">
</body>
</html>

The g-computation algorithm can be found at https://github.roche.com/lil128/covadj/blob/9deb581a9c25c25f5c62b133d86e53ee742c5e22/R/statistics.R#L5
where fit is the logistic regression fit object using `glm` and `trt_var` is the treatment variable used. This functions provides the standard errors and estimates; the CI are not included but can be derived using normal distribution

This output is approved already but for the layout we can further evaluate if this is appropriate/feasible in tern

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by clarkliming** [comment]
Hi @khatril could you please refine this issue and evaluate if this is possible to implement

**Comment by shajoezhu** [comment]
let's use our current code for a design first

**Comment by edelarua** [comment]
Transferred this issue to sme-tasks repo: https://github.com/insightsengineering/sme-tasks/issues/643
