### ISSUE TITLE
Investigate warnings from `g_lineplot`

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/tern#820]
Find the cause of warnings in `g_lineplot` tests (these have been removed for now):

```r
adsl <- tern_ex_adsl
adlb <- tern_ex_adlb %>% dplyr::filter(ANL01FL == "Y", PARAMCD == "ALT", AVISIT != "SCREENING")
adlb$AVISIT <- droplevels(adlb$AVISIT)
adlb <- dplyr::mutate(adlb, AVISIT = forcats::fct_reorder(AVISIT, AVISITN, min))

testthat::test_that("g_lineplot works with default settings", {
  testthat::expect_silent(g_lineplot(adlb, adsl))
})

testthat::test_that("g_lineplot works with custom settings and statistics table", {
  testthat::expect_silent(g_lineplot(
    adlb,
    adsl,
    strata = control_lineplot_vars(strata = NULL),
    mid = "median",
    table = c("n", "mean", "mean_ci"),
    control = control_summarize_vars(conf_level = 0.80),
    title = "Plot of Mean and 80% Confidence Limits by Visit",
    y_lab = "Lab Test",
    subtitle = "Laboratory Test:",
    caption = "caption"
  ))
})
```
Warnings occurred after updating ci-image for this PR: https://github.com/insightsengineering/tern/issues/817

**Comment by Melkiades** [comment]
This is the culprit:
```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Error ('test-g_lineplot.R:9'): g_lineplot works with default settings ───────
  Error in `eval(code, test_env)`: THIS IS THE WARNING 1: Each row in `x` is expected to match at most 1 row in `y`.
  i Row 1 of `x` matches multiple rows.
  i If multiple matches are expected, set `multiple = "all"` to silence this warning.
  ── Error ('test-g_lineplot.R:28'): g_lineplot works with custom settings and statistics table ──
  Error in `eval(code, test_env)`: THIS IS THE WARNING 2: Each row in `x` is expected to match at most 1 row in `y`.
  i Row 1 of `x` matches multiple rows.
  i If multiple matches are expected, set `multiple = "all"` to silence this warning.
```

Further information regarding this can be found [here](https://www.tidyverse.org/blog/2023/01/dplyr-1-1-0-joins/):

> Company A matches correctly, but since we only joined on the company id, we get multiple matches for each of company B's transactions and end up with more rows than we started with. This is a problem, as we were expecting a 1:1 match for each row in transactions. Multiple matches in equality joins like this one are typically unexpected (even though they are baked in to SQL) so we’ve also added a new warning to alert you when this happens. If multiple matches are expected, you can explicitly set multiple = "all" to silence this warning. This also serves as a code “sign post” for future readers of your code to let them know that this is a join that is expected to increase the number of rows in the data. If multiple matches aren’t expected, you can also set multiple = "error" to immediately halt the analysis. We expect this will be useful as a quality control check for production code where you might rerun analyses with new data on a rolling basis.

I will add `multiple = "all"` for the moment. I do not know if it is the expected behavior (to grow the data) but it seems so to me.
