### ISSUE TITLE
Add a Bland-Altman plotting function

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tern#851]
Based on https://github.com/insightsengineering/tern/issues/850, we now add a plotting method.

To do:
- [ ] Create a `plot` method for `bland_altman` object
    - [ ] Create an object as described in https://github.com/insightsengineering/tern/issues/850
    - [ ] Add an S3 `plot` method by defining `plot.bland_altman(x, xlab, ylab, title, ylim)`
    - [ ] use `ggplot2` for the plotting
- [ ] Add a test using `vdiffr`
- [ ] Add to NEWS

**Comment by shajoezhu** [comment]
closed by `g_bland_altman` function
