### ISSUE TITLE
Activate and further test negative binomial functionality

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tern#857]
Depends on #856 

Now that we have the helper function in the package, we can activate the functionality and check that it works really correctly for the user.

To do:
- [ ] Modify [`h_glm_count()`](https://github.com/insightsengineering/tern/blob/main/R/summarize_glm_count.R#L174) such that we can use `distribution = "negbin"`
	- [ ] Adapt / add corresponding test in https://github.com/insightsengineering/tern/blob/main/tests/testthat/test-summarize_glm_count.R
- [ ] Add an integration test for `s_glm_count()` similar as [here](https://github.com/insightsengineering/tern/blob/main/tests/testthat/test-summarize_glm_count.R#L188)
	- [ ] but compare actual numbers with SAS implementation results (e.g. use `sasr` for this)
- [ ] Add an integration test for `summarize_glm_count()` similar as [here](https://github.com/insightsengineering/tern/blob/main/tests/testthat/test-summarize_glm_count.R#L260)
- [ ] Add a NEWS entry for this new feature

**Comment by shajoezhu** [comment]
closed in https://github.com/insightsengineering/tern/pull/1163
