### ISSUE TITLE
Prepare for CRAN release

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/tern#859]
### Preparing for CRAN initial submission checks

- [x] all function documentation must have a `\value{}` entry, as produced by the `@return` roxygen2 tag 
        https://github.com/insightsengineering/tern/issues/871
- [x] All CRAN package urls must be of the canonical form (e.g., `https://cran.r-project.org/package=rtables`, NOT the `.../web/packages/...` version
- [x] #885
- [x] #930
- [x] #965
- [x] #958
- [x] #886
- [x] #925
- [x] #887
- [x] #888
- [x] #889

CRAN guidance:

> If there are references describing the methods in your package, please
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
auto-linking. (If you want to add a title as well please put it in
quotes: "Title")

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gmbecker** [comment]
@edelarua please fix the labels and add this to the project board (it will be for next increment, but should be in the backlog) as I don't seem to be able to.

**Comment by shajoezhu** [comment]
thanks Gabe, this is very helpful
