### ISSUE TITLE
Create release tag 0.8.1

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#862]
- [x]  Bump version to 0.8.1
- [x]  check and update README and NEWS.md 0.8.0 -> 0.8.1
- [x]  tag github release 0.8.1
- [x]  update citril DESCRIPTION of tern >= 0.8.1 https://github.com/insightsengineering/citril/pull/216
- [x]  update chevron DESCRIPTION of tern >= 0.8.1 https://github.com/insightsengineering/chevron/pull/459

**Comment by Melkiades** [comment]
there is an error on main to be fixed though
