### ISSUE TITLE
cran does not allow  `c()` as standard parameter value (use list instead)

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#873]
see ref: https://github.com/insightsengineering/chevron/pull/465

**Comment by shajoezhu** [comment]
Renaming the issue to "cran does not allow  `c()` as standard parameter value (use list instead)", as remotes issue is not related here anymore

**Comment by Melkiades** [comment]
> Can you please elaborate more about it please? It's linked to the other issue but I can't find any reference explaining why CRAN would complain.
> 
> Please also note that list is significantly different to the (character) vector. It's designed for much more complex data structure which we don't need for most (all?) of the cases. Maybe we just need to replace `c()` with `character()`?

We do not think this is not any longer an issue. If something comes up in the validation we can open this again. @shajoezhu fyi
