### ISSUE TITLE
Add `median_range` statistic for `summarize_vars`

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/tern#883]
### Feature description

The `median_range` statistic (i.e. `Median (Min - Max)`) is used in several FDA standard tables and would be useful to have as an option for `summarize_vars` instead of requiring a custom analysis function.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by shajoezhu** [comment]
this is a great idea!
