### ISSUE TITLE
[Question]: summarize_vars or analyze_vars?

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#900]
### What is your question?

https://github.com/insightsengineering/tern/blob/e3e5d789a5b0051eeed88b445e7cfc9bc73c91b4/R/summarize_variables.R#L731

`summarize_vars` sounds like using `summarize_row_groups`, but actually using `analyze`.

similar functions like `summarize_num_patients` and `analyze_num_patients` looks good

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
This is a very good question. I completely agree with you and I found it at the time utterly confusing. The problem is that changing this naming would produce a large overhead downstream as many commonly used functions present this.

**Comment by Melkiades** [comment]
related to https://github.com/insightsengineering/formatters/issues/147. My solution is to create the needed analogs for the used functions in the templates so to have a smooth transition on one side and the summarize version for when is needed. @edelarua fyi

**Comment by Melkiades** [comment]
tracked also by https://github.com/insightsengineering/tlg-catalog/issues/44

**Comment by shajoezhu** [comment]
Liming is right, I agree. I would suggest the following
1. keep the function summarize_vars to avoid breakchange for now，(deprecate in future versions maybe, but this is so widely used, so might be difficult) however in its documentation refer to analyze_vars
2. create analyze_vars function, basically duplicate summarize_vars
3. replace all use case of summarize_vars by analyze_vars in nest packages

**Comment by Melkiades** [comment]
> Liming is right, I agree. I would suggest the following
> 
> 1. keep the function summarize_vars to avoid breakchange for now，(deprecate in future versions maybe, but this is so widely used, so might be difficult) however in its documentation refer to analyze_vars
> 2. create analyze_vars function, basically duplicate summarize_vars
> 3. replace all use case of summarize_vars by analyze_vars in nest packages

I think it is better not to make shallow copies as this would be very dangerous for how healthy the code turns out to be at the end of the deprecation cycle. Also, not all the summarize/analyze functions present only one or the other behavior. I will propose a solution based on aliases.

**Comment by Melkiades** [comment]
btw I found that (ofc) this is a common case: [stackoverflow](https://stackoverflow.com/questions/10099128/are-there-best-recommended-practices-to-follow-when-renaming-functions-in-a-new)
