### ISSUE TITLE
[change response sequence]: <d_onco_rsp_label>

### ISSUE THREAD

**Issue by Teninq** [insightsengineering/tern#901]
### Feature description

The level of response seems not in a good sequence, the `Not Evaluable (NE)` should be displayed after `Stable Disease (SD)` .

I have updated the `d_onco_rsp_label` function and you can take it as reference.
```
{
  x <- as.character(x)
  desc <- c(CR = "Complete Response (CR)", PR = "Partial Response (PR)",
            MR = "Minimal/Minor Response (MR)", MRD = "Minimal Residual Disease (MRD)",
            SD = "Stable Disease (SD)", PD = "Progressive Disease (PD)",
            `NON CR/PD` = "Non-CR or Non-PD (NON CR/PD)",  NE = "Not Evaluable (NE)",
            `NE/Missing` = "Missing or unevaluable", Missing = "Missing",
            `NA` = "Not Applicable (NA)", ND = "Not Done (ND)")
  values_label <- vapply(X = x, FUN.VALUE = character(1), function(val) {
    if (val %in% names(desc))
      desc[val]
    else val
  })
  return(factor(values_label, levels = desc))
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by clarkliming** [comment]
I think we should include the levels that we have, be default. no need to add new levels that has no values.

**Comment by Teninq** [comment]
> I think we should include the levels that we have, be default. no need to add new levels that has no values.

Agree.
