### ISSUE TITLE
remove the text 'baseline status' from the values displayed under the by-variable 'Baseline Status'

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#947]
- [ ] please remove the text 'baseline status' from the values displayed under the by-variable 'Baseline Status', this is not taken from the data and it is redundant. ![image](https://github.com/insightsengineering/sme-tasks/assets/128674103/9d7b470a-77ce-4092-b2fc-b0cfcecaec38)

_Originally posted by @tianfang1121 in https://github.com/insightsengineering/sme-tasks/issues/631#issuecomment-1575919526_

**Comment by clarkliming** [comment]
@shajoezhu do you have any idea why these are added? is there any stories behind? or @barnett11 do you know it?

**Comment by barnett11** [comment]
> @shajoezhu do you have any idea why these are added? is there any stories behind? or @barnett11 do you know it?

I've no idea sorry @clarkliming , I've not seen this before, it certainly is not needed
