### ISSUE TITLE
left_join is not imported

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#948]
https://github.com/insightsengineering/tern/blob/cefccf2bff1c28cf146ac1a18f1057e3be7dad9f/R/kaplan_meier_plot.R#L974

https://github.com/insightsengineering/tern/blob/main/R/package.R

https://github.com/insightsengineering/tern/blob/main/DESCRIPTION

**Comment by clarkliming** [comment]
causing issues downstream 

https://github.com/insightsengineering/chevron/actions/runs/5172562000/jobs/9317022934

**Comment by danielinteractive** [comment]
Yeah BAC was also impacted
