### ISSUE TITLE
rename time_unit_output to num_pt_year 

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#973]
https://github.com/insightsengineering/tern/blob/395503f1298e8ec8758d56a8d17af1ccfa1d4657/R/control_incidence_rate.R#L26

the argument name is misleading. if time_unit_input is year, why time_unit_output become a number?

**Comment by shajoezhu** [comment]
rename time_unit_output to number_of_patient_year

**Comment by clarkliming** [comment]
please also consider the default the value: shall we use 1 or 100 ?

**Comment by edelarua** [comment]
> please also consider the default the value: shall we use 1 or 100 ?

@clarkliming I've updated the default value to 100. Thanks for the feedback!
