### ISSUE TITLE
CRAN release 0.8.4

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#977]
- [x] #978
- [x]  create cran_releae_0.8.4_branch
- [x]  check NEWS.md, README, update DESCRIPTION
- [x]  Submission to CRAN
- [x]  Address any CRAN feedback
- [x]  Acceptance on CRAN
- [ ]  merge cran_releae_0.8.4_branch
- [ ]  tag v0.8.4

**Comment by Melkiades** [comment]
What is the timeline for this? @gmbecker repeatedly said that CRAN is not happy with too frequent releases

**Comment by shajoezhu** [comment]
before 2023-07-04
