### ISSUE TITLE
default precisions for s_summary.numeric

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#979]
3.1.	Measures of location and dispersion (e.g., mean, median, variance, SD, SE, and corresponding confidence intervals) are displayed with 1 more decimal place of precision than the most precise collected data.
3.2.	Percentiles (eg, Q1, Q3, 99th percentile) are displayed with 1 more decimal place of precision than the most precise collected data.
3.3.	When data are summarized in the same unit as collected, the minimum and the maximum are displayed with the same number of decimal places of precision as the most precise collected data.

_Originally posted by @barnett11 in https://github.com/insightsengineering/chevron/pull/343#discussion_r1052047637_

**Comment by clarkliming** [comment]
currently we have inconsistent which I believe could be refined.

```
> tern:::.a_summary_numeric_formats
                   n                  sum                 mean 
               "xx."               "xx.x"               "xx.x" 
                  sd                   se              mean_sd 
              "xx.x"               "xx.x"        "xx.x (xx.x)" 
             mean_se              mean_ci             mean_sei 
       "xx.x (xx.x)"     "(xx.xx, xx.xx)"     "(xx.xx, xx.xx)" 
            mean_sdi            mean_pval               median 
    "(xx.xx, xx.xx)"              "xx.xx"               "xx.x" 
                 mad            median_ci            quantiles 
              "xx.x"     "(xx.xx, xx.xx)"        "xx.x - xx.x" 
                 iqr                range                   cv 
              "xx.x"        "xx.x - xx.x"               "xx.x" 
                 min                  max         median_range 
              "xx.x"               "xx.x" "xx.x (xx.x - xx.x)" 
           geom_mean              geom_cv 
              "xx.x"               "xx.x" 
```

if range has 1 dp, then mean should have 2 dp

**Comment by shajoezhu** [comment]
hey @khatril , what do you think? I have no strong preference here. perhaps we should also consider, set them as the most commonly used?

**Comment by Melkiades** [comment]
> 3.1. Measures of location and dispersion (e.g., mean, median, variance, SD, SE, and corresponding confidence intervals) are displayed with 1 more decimal place of precision than the most precise collected data. 3.2. Percentiles (eg, Q1, Q3, 99th percentile) are displayed with 1 more decimal place of precision than the most precise collected data. 3.3. When data are summarized in the same unit as collected, the minimum and the maximum are displayed with the same number of decimal places of precision as the most precise collected data.
> 
> _Originally posted by @barnett11 in [insightsengineering/chevron#343 (comment)](https://github.com/insightsengineering/chevron/pull/343#discussion_r1052047637)_

If this is the standard we can change the internal standard in tern to reflect that. We need only to be certain that there is alignment in what the new standards should be

**Comment by telepath37** [comment]
For 3.3 in the original issue, and specifically looking at variable such as STUDY DAY, does 3.3 suggest we should show min-max in its original precision, i.e. whole number?

**Comment by anajens** [comment]
For reference, GDSR update from March 2023 includes the following details on number of decimal places:

![image](https://github.com/insightsengineering/tern/assets/43623360/6006f7c6-394c-4387-a0db-631edd7a8ee2)

**Comment by clarkliming** [comment]
> For reference, GDSR update from March 2023 includes the following details on number of decimal places:

Is this something internal that should not be shared here?

**Comment by Melkiades** [comment]
Possible to achieve this now by doing `.formats = "auto"` from `analyze_vars()`
