### ISSUE TITLE
Cautiously integrate/introduce expanded and more elastic standards for summaries' formats

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#994]
Function to be added: https://github.com/insightsengineering/chevron/blob/833caa90c6469f5f5a4c74fbd2fdbf2ef13e238c/R/rtables_utils.R#L399 

Originally proposed @clarkliming 

For the moment, I would add it as a possibility, then we can roll out older standards gradually.

**Comment by clarkliming** [comment]
@barnett11 could you please evaluate the formats provided are good or not?

**Comment by clarkliming** [comment]
by the way, may I ask if it is too much to store the format in every cell? or, after the row is created, use the format in whole row?

**Comment by Melkiades** [comment]
> by the way, may I ask if it is too much to store the format in every cell? or, after the row is created, use the format in whole row?

I do not know what exactly you mean but both things are possible. It is the main difference between using only in_rows and rcell. Of course they can be combined. Always lowest level format has precedence

**Comment by clarkliming** [comment]
oh, what I mean is that if we only want to update the formats for whole row, shall we still, use make_afun to do so? (actually never mind this; adding formats to cell or row both works. I was just thinking that the storage (too many repetitions of storing formats if every cell has  a format function)

**Comment by Melkiades** [comment]
To add this I thought about using different lists of defaults and transforming it in a list. @BFalquet, we can talk about this if you can

**Comment by Melkiades** [comment]
The PR related to this, @clarkliming, does not add the possibility of using other standards for now. It is a large refactoring in how the defaults are stored and so on. For the moment, adding specific formats is very easy with `.formats` so I think it is fine to keep tlg and chevron defaults in separate places
